name: hide-and-seek
version: '1.21.1.0.0-SNAPSHOT'
main: dev.slne.hideandnseek.HideAndSeek
api-version: '1.21'
authors: [ SLNE Development ]
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
